name: 'socialminer'
version: '2.0.0'
config-version: 2
profile: 'socialminer'
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

models:
  socialminer:
      materialized: table
      staging:
        materialized: view