jaffle_shop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: '1234'
      port: 5432
      dbname: postgres
      schema: dbt_tutorial
      threads: 4