socialminer:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 172.17.0.2
      user: postgres
      password: '1234'
      port: 5432
      dbname: postgres
      schema: public
      threads: 4